### ISSUE TITLE
install No prebuilt binaries found (target=v4.4.7 arch=x64 platform=win32)

### ISSUE THREAD

**Issue by user8614** [nolanlawson/hello-electron-with-pouchdb#5]
hello nolan.
please help me.
i'm spend many time for install pouchdb in windows but this github solution not work for me.
i need level db in project and leveldown dont install.
i'm don't want browser database and i want use pouchdb in one desktop app with no dependency to browser.i used nedb but file database is plaintext and security is very important for me .
leveldown madule delete from hello-electron-with-pouchdb\node_modules\pouchdb\node_modules after prebuild --install command then show this error

> hello-electron-with-pouchdb@1.0.0 postinstall D:\test 3\hello-electron-with-pouchdb
> bash postinstall.sh

postinstall.sh: line 5: cd: node_modules/leveldown: No such file or directory

---

D:\test 3>git clone https://github.com/nolanlawson/hello-electron-with-pouchdb
Cloning into 'hello-electron-with-pouchdb'...
remote: Counting objects: 87, done.
remote: Total 87 (delta 0), reused 0 (delta 0), pack-reused 87
Unpacking objects: 100% (87/87), done.
Checking connectivity... done.

D:\test 3>cd hello-electron-with-pouchdb

D:\test 3\hello-electron-with-pouchdb>npm install
npm WARN package.json hello-electron-with-pouchdb@1.0.0 No repository field.
npm WARN package.json hello-electron-with-pouchdb@1.0.0 No license field.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> electron-prebuilt@1.3.4 postinstall D:\test 3\hello-electron-with-pouchdb\node_modules\electron-prebuilt
> node install.js

|
|

> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "D:\test 3\hello-electron-with-pouchdb\node_modules\pouchdb\node_modules\websql\node_modules\sqlite3\lib\binding\node-v46-win32-x64
\node_sqlite3.node" is installed via remote

> leveldown@1.4.6 install D:\test 3\hello-electron-with-pouchdb\node_modules\pouchdb\node_modules\leveldown
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v4.4.7 arch=x64 platform=win32)
prebuild ERR! configure error
prebuild ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
prebuild ERR! stack     at failNoPython (D:\test 3\hello-electron-with-pouchdb\node_modules\pouchdb\node_modules\leveldown\node_modules\prebuild\node_
modules\node-gyp\lib\configure.js:449:14)
prebuild ERR! stack     at D:\test 3\hello-electron-with-pouchdb\node_modules\pouchdb\node_modules\leveldown\node_modules\prebuild\node_modules\node-g
yp\lib\configure.js:404:11
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
prebuild ERR! not ok
prebuild ERR! build Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
prebuild ERR! build     at failNoPython (D:\test 3\hello-electron-with-pouchdb\node_modules\pouchdb\node_modules\leveldown\node_modules\prebuild\node_
modules\node-gyp\lib\configure.js:449:14)
prebuild ERR! build     at D:\test 3\hello-electron-with-pouchdb\node_modules\pouchdb\node_modules\leveldown\node_modules\prebuild\node_modules\node-g
yp\lib\configure.js:404:11
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN optional dep failed, continuing leveldown@1.4.6

> hello-electron-with-pouchdb@1.0.0 postinstall D:\test 3\hello-electron-with-pouchdb
> bash postinstall.sh

postinstall.sh: line 5: cd: node_modules/leveldown: No such file or directory
postinstall.sh: line 7: ../.bin/node-gyp: No such file or directory

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hello-electron-with-pouchdb@1.0.0 postinstall: `bash postinstall.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the hello-electron-with-pouchdb@1.0.0 postinstall script 'bash postinstall.sh'.
npm ERR! This is most likely a problem with the hello-electron-with-pouchdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hello-electron-with-pouchdb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls hello-electron-with-pouchdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test 3\hello-electron-with-pouchdb\npm-debug.log

**Comment by nolanlawson** [comment]
Since there are no prebuilt binaries, you may need to set up your machine for Windows native modules. You'll need to install a special npm package using Power Shell in Admin mode, but it should work: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#environment-setup-and-configuration

**Comment by xx0r** [comment]
I can confirm it works on **Windows 10 x64.** 
Simply went with **npm install -g windows-build-tools** with admin rights and it just did the trick

**Comment by nolanlawson** [comment]
yes that is usually the fix for Node native Windows stuff

**Comment by nolanlawson** [comment]
please reopen if that doesn't work

**Comment by mauriv992** [comment]
help me!!!!!! 
I can not solve this error

npm i serialport

> @serialport/bindings@2.0.2 install C:\Users\sony vaio\Desktop\AappProyectoSitioweb\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.9.4 runtime=node arch=x64 platform=win32)

C:\Users\sony vaio\Desktop\AappProyectoSitioweb\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '201'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sony vaio\Desktop\AappProyectoSitioweb\node_modules\@serialport\bindings
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN AappProyectoSitioweb@1.0.0 No description
npm WARN AappProyectoSitioweb@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.2 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sony vaio\AppData\Roaming\npm-cache\_logs\2018-09-16T00_21_31_094Z-debug.log

**Comment by nolanlawson** [comment]
Please see https://github.com/nolanlawson/hello-electron-with-pouchdb/issues/11#issuecomment-433749339

**Comment by amanda13franco** [comment]
Necesito ayuda porfavor
prebuild-install WARN install No prebuilt binaries found (target=10.15.1 runtime=node arch=x64 platform=win32)

C:\Users\amand\OneDrive\Escritorio\proyectojaja\node_jaja\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\amand\AppData\Local\Programs\Python\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\amand\OneDrive\Escritorio\proyectojaja\node_jaja\node_modules\serialport
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN jaja_node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@6.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amand\AppData\Roaming\npm-cache\_logs\2019-02-10T05_15_23_804Z-debug.log
