### ISSUE TITLE
postinstall.sh has a different path to electron than what is installed via package.json

### ISSUE THREAD

**Issue by delebash** [nolanlawson/hello-electron-with-pouchdb#6]
Window7 x64
Node 6.6.0 x64
Npm 3.10.8

package.json installs electron-prebuilt but postintall.sh is looking for electron instead of electron-prebuilt
VERSION=$(node --eval "console.log(require('./node_modules/electron/package.json').version);")

I changed my package.json to  install electron instead since electron-prebuilt is being deprecated 

Thanks for the demo it really helped

**Comment by nolanlawson** [comment]
I don't understand this issue. Could you please explain in more detail?

**Comment by anithri** [comment]
I just ran into this exact problem. after a git clone cd to the dir and `npm install` which failed.

```
> hello-electron-with-pouchdb@1.0.0 postinstall /tmp/hello-electron-with-pouchdb
> bash postinstall.sh

module.js:328
    throw err;
    ^

Error: Cannot find module './node_modules/electron/package.json'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at [eval]:1:13
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:410:26)
    at node.js:578:27
    at nextTickCallbackWith0Args (node.js:419:9)
gyp WARN install got an error, rolling back install
```

the postinstall script expects electron to be in a particular path: `/tmp/hello-electron-with-pouchdb/./node_modules/electron/package.json`

the package.json file however is set to electron-prebuilt, which apparently has a different path.

I did the same thing as @delebash changed `"electron-prebuilt": "^1.2.0"` to `"electron": "^1.2.0"`

after I did that, `npm install` worked and I could run the app.

**Comment by delebash** [comment]
@anithri Yep that's it.  Thanks for the better explanation.

**Comment by nolanlawson** [comment]
fixed thanks to `electron-rebuild`
