### ISSUE TITLE
Just Info for Windows users who want to use LevelDb

### ISSUE THREAD

**Issue by delebash** [nolanlawson/hello-electron-with-pouchdb#7]
You have to build the leveldb module for electron

Instead of trying to build manually (which I never got to work) use electron-rebuild module
https://github.com/electron/electron-rebuild.  

Remove `"postinstall": "bash postinstall.sh"` from you package.json as we are running this manually and won't need it

Commands to run

`npm install electron-rebuild --save-dev`

then paste into your terminal

`./node_modules/.bin/electron-rebuild -w leveldown -p`

**Note:** The switches are very important as the example on electron-rebuild's site for windows does not work so use above command

I also changed electron-prebuilt to just electron in package.json as electron replaces electron-prebuilt.  I installed the latest version of everything in package.json, although I suspect that is not needed

Thanks to @tobico https://github.com/electron/electron-rebuild/issues/15

**Comment by Steviey** [comment]
Another method for Win 7:

Remove "postinstall": "bash postinstall.sh" from you package.json as we are running this manually and won't need it

Node-gyp-Fix:  Error  binding.gyp not found...
1. cd node_modules/leveldown
2. node-gyp configure
3. set HOME=C:\a\node_modules.electron-gyp (optional)
   node-gyp rebuild --target=1.4.3 --arch=x64 --dist-url=https://atom.io/download/atom-shell

After that LevelDb-check passes successfully.

**Comment by nolanlawson** [comment]
should be fixed thanks to `electron-rebuild`
